# Generated by Django 4.2.1 on 2023-06-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_customer_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(default='avi.jpeg', null=True, upload_to=''),
        ),
    ]
